# Generated by Django 4.2.7 on 2023-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('Address', models.TextField(default='Address')),
                ('Patients_info', models.TextField(default='IFO')),
                ('Type', models.CharField(choices=[('Male', 'Male'), ('Fmale', 'Fmale')], max_length=100)),
                ('Ray', models.ImageField(default='', upload_to='photos%y/%m/%d')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
